### ISSUE TITLE
Extensionless File

### ISSUE THREAD

**Issue by Glazelf** [Leanny/splat3#2]
In 1bef4e3979c32c9a188cfdff444ff660911cfd71 you added a latest parameter, which is cool.
But often it can be hard to read programmatically without an extension.
Stuff like node `fs` refuses to read extensionless files.

Could you consider making it a `.json`, `.txt` or something?
I think `.json` makes the most sense.

**Comment by Leanny** [comment]
Hello! This is a symbolic link, so when you use the api you can for example now access the files via [latest](https://leanny.github.io/splat3/data/mush/latest/WeaponInfoSpecial.json) instead of via [610](https://leanny.github.io/splat3/data/mush/610/WeaponInfoSpecial.json).
Check your git config for [core.symlinks](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresymlinks]

**Comment by Glazelf** [comment]
Ah that makes more sense. I'm having some trouble getting that to work properly with node fs but it might also be because of how importing submodules works or something. It works fine on my Windows machine but on my Ubuntu enviroment it treats `latest` as a directory.
I'll look into it later, thanks for the pointer.
